### ISSUE TITLE
Search functionality not getting relevent events to the search query.

### ISSUE THREAD

**Issue by anasfik** [UTXOnly/nost-py#53]
Hello there,

firstly, I appreciate your help here, and sorry for opening this issue late.

we do run nostr-py on a Linux VM, we cloned the repo, and followed instructions (the new readme precisely), there is the env variables:
```env
PGDATABASE=nostr
PGUSER=nostr
PGPASSWORD=nostr
PGPORT=5432
PGHOST=172.28.0.4
DD_ROLE_PASSWORD=
DD_ROLE_NAME=
DD_ENV=
DD_HOSTNAME=
DOMAIN_NAME=tribly.co
HEX_PUBKEY=a
CONTACT=your_email@email.com
ENV_FILE_PATH=./docker_stuff/.env
NGINX_FILE_PATH=/etc/nginx/sites-available/default
VERSION=v0.8
```

running the commands at `menu.py` to set up other things like Nginx, encrypting/decrypting env file... is ensured and confirmed to be done this time.

after starting the containers, running `docker-compose ps` gives me:

![image](https://github.com/UTXOnly/nost-py/assets/25140579/eec2f875-52b3-48fd-9e35-119ae1a457a7)

also running `netstat -tulnp` to ensure that there is a listener on port 8008 gives:
![image](https://github.com/UTXOnly/nost-py/assets/25140579/817a5297-b1be-48cd-ab06-dcaa2f9c2518)

also, I confirmed the reverse proxying of it by nginx to the domain, and so it is running at [http://tribly.co/](http://tribly.co/), and the WebSocket at [ws://tribly.co](ws://tribly.co) (no TLS configuration is done yet).

now using Insomnia (an HTTP client) to try using it, I started by sending a random event (copied it from a different source, but it is confirmed to be valid, its id and sig are valid and verified):

```json
[
	"EVENT",
	{
		"id": "a22aec54f45b1a33ebe2c7c545aa06aad9547f873810f933ed19d27ce489ad1f",
		"pubkey": "8b2ff7ceb4a1ea558bb929ce0d3513dfeca2cab712fd149551a961c822ace218",
		"created_at": 1706620119,
		"kind": 31990,
		"tags": [
			[
				"d",
				"7ab57c96fcb644c9d0d9ca0c93f40a863f7e8f6b33a4835b50ff3b3ac5c23129"
			],
			[
				"k",
				"30402"
			],
			[
				"web",
				"https://shopstr.store/<bech-32>",
				"npub"
			]
		],
		"content": "",
		"sig": "aa0dffe7c09c0053ba1ca61c56e1955f04b75d28602120937f780e2c391e5529c1fc8bd048b4b9abe5dcc25f281a8c6740466b86f5cc5cbfcc0833a4ebe3db71"
	}
]
```

the relay responds with an OK:

```json
[
	"OK",
	"a22aec54f45b1a33ebe2c7c545aa06aad9547f873810f933ed19d27ce489ad1f",
	true,
	""
]
```

which is all good.

now let's query it with:
```
[
	"REQ",
	"aaaaaa",
	{
		"kinds": [31990]
	}
]
```
the relay responds with what we need and returns the event
![image](https://github.com/UTXOnly/nost-py/assets/25140579/8780054b-ef72-4073-83cc-65461ad5f3cb)

now let's query with search, saying that from a text field in the UI, a user writes "something-very-random", hoping to get any events that contains it either in their content or tags:
```json
[
	"REQ",
	"aaaaaxa",
	{
		"kinds": [31990],
		"search": "something-very-random"
	}
]
```

sending it, it still gets us back the event, even if the search query makes no sense with that event:
![image](https://github.com/UTXOnly/nost-py/assets/25140579/1e70feec-b6c9-4269-b620-6da2fa8da81b)

what was expected here is that the search functionality would be applied and get events that contain the search query in it, like if we search "shopstr.store", so the results would be relevant in some way.

**Comment by anasfik** [comment]
update: moved it to [relay.tribly.co](relay.tribly.co) instead of [tribly.co](tribly.co)

**Comment by anasfik** [comment]
update: the relay is on `https://relay.tribly.co` instead of `tribly.co`

**Comment by UTXOnly** [comment]
Hey @anasfik thank you for taking the time to open this and bring this to my attention!

I believe I found the issue [link to problematic query](https://github.com/UTXOnly/nost-py/blob/a66fb60ed9464dc0e76164c38196d12a95fc09ab/docker_stuff/python_stuff/event_classes.py#L307-L310)

```
            if global_search:
                search_clause = self._search_tags(global_search)
                search_content = self._search_content(global_search)
                self.where_clause += f" AND ({search_content} OR {search_clause})"
```

I am constructing a query that returns search matches between `tags` and `content` columns but the `OR` clause at the end of the query is causing the query to return the false positive result.

I think this should instead be a nested query, more like:

```
 AND EXISTS ( SELECT 1 FROM jsonb_array_elements(tags) as elem WHERE elem @> '{tag_pair}' OR content LIKE '%{search_item}%')
```
This way the query will only return results if a search result matches in either `tags` or `content` columns. 

I will link the PR to this issue once I have had a chance to refactor and test.

**Comment by UTXOnly** [comment]
Hey @anasfik I just pushed up the linked PR on the `search_fix` branch. I have tested this with a command line client I made and I believe it has resolved the issue.

Could you please test with your notes and let me know if this resolved the false positives returned in the search?

Thanks!

**Comment by anasfik** [comment]
Thank you @UTXOnly for your contributions.

I pulled and configured the "search_fix" branch in our VM:
![image](https://github.com/UTXOnly/nost-py/assets/25140579/7b57ae20-536d-41b9-b406-3b31b0dee836)

made sure to re-run the relay containers (stopping previous ones completely, then running them again with the new git changes on the search_fix branch), it runs successfully, but I'm afraid the issue still can be reproduced, sending a request with a search query:
![image](https://github.com/UTXOnly/nost-py/assets/25140579/0fad93c2-a771-4486-a22a-d4d17da57cac)

the query:
```json
[
	"REQ",
	"something",
	{
		"kinds": [31990],
		"search": "something-very-random-djfibidufdf"
	}
]
```

keep returning non-relevant events/all events of that kind, what do you recommend for this?

**Comment by UTXOnly** [comment]
Hey @anasfik ,

Thanks for trying that and following up. I am unable to reproduce the behavior on that branch after recreating containers (and images)


### Step 1
Add the event above to my relay

```[
	"EVENT",
	{
		"id": "a22aec54f45b1a33ebe2c7c545aa06aad9547f873810f933ed19d27ce489ad1f",
		"pubkey": "8b2ff7ceb4a1ea558bb929ce0d3513dfeca2cab712fd149551a961c822ace218",
		"created_at": 1706620119,
		"kind": 31990,
		"tags": [
			[
				"d",
				"7ab57c96fcb644c9d0d9ca0c93f40a863f7e8f6b33a4835b50ff3b3ac5c23129"
			],
			[
				"k",
				"30402"
			],
			[
				"web",
				"https://shopstr.store/<bech-32>",
				"npub"
			]
		],
		"content": "",
		"sig": "aa0dffe7c09c0053ba1ca61c56e1955f04b75d28602120937f780e2c391e5529c1fc8bd048b4b9abe5dcc25f281a8c6740466b86f5cc5cbfcc0833a4ebe3db71"
	}
]
```
![step1](https://github.com/UTXOnly/nost-py/assets/49233513/f44e3773-721d-46e0-a8df-982ce83bcc5f)

### Step 2

Query for event using query depicted above

```
[
	"REQ",
	"something",
	{
		"kinds": [31990],
		"search": "something-very-random-djfibidufdf"
	}
]
```

Received `EOSE` response depicted below:

![step2](https://github.com/UTXOnly/nost-py/assets/49233513/e4952ca0-2154-43f6-97c7-9beed9ff15d8)


### Step 3
Adjust query to search for the value of the `#d` tag:

```
[
"REQ",
"something",
{
"kinds": [31990],
"search": "7ab57c96fcb644c9d0d9ca0c93f40a863f7e8f6b33a4835b50ff3b3ac5c23129"
}
]
```
![step3](https://github.com/UTXOnly/nost-py/assets/49233513/509025b9-b875-4b0a-9c04-e3fcc06bad87)


The search correctly only returned the event when searching for the `["#d", "7ab57c96fcb644c9d0d9ca0c93f40a863f7e8f6b33a4835b50ff3b3ac5c23129" ]` tag



I think what is happening is that the containers were stopped but then rebuilt with the same image with the old code. Can you try removing the docker image entirely and rebuilding a fresh image and let me know if the issue persists?

**Comment by anasfik** [comment]
Hey, thank you for following up with this.

Yes, your example is working (tried that on relay.nostpy.lol), searching for "7ab57c96fcb644c9d0d9ca0c93f40a863f7e8f6b33a4835b50ff3b3ac5c23129" returns that event.

However, I guess you would get a more general idea about this if you error-check for more search queries, running this as example:

```json
[
	"REQ",
	"somethdddisssng",
	{
		"kinds": [31990],
		"search": "non-sense"
	}
]
```

still gets the event.

**Comment by UTXOnly** [comment]
Hey @anasfik ,

Thanks for testing again and providing your results, your latest test uncovered a bug where `search` filters were not being added to the redis cache key, resulting in `REQ` with `search` filters to only store the `kind` filter and return a false positive. 

Example:
```
2024-05-11 14:09:36,949 - DEBUG - Fiters are: {'kinds': [31990], 'search': '7ab57c96fcb644c9d0d9ca0c93f40a863f7e8f6b33a4835b50ff3b3ac5c23129'}

2024-05-11 14:09:36,963 - DEBUG - Caching results , keys: {'kinds': [31990]}   value is : [[{"id": "a22aec54f45b1a33ebe2c7c545aa06aad9547f873810f933ed19d27ce489ad1f", "pubkey": "8b2ff7ceb4a1ea558bb929ce0d3513dfeca2cab712fd149551a961c822ace218", "kind": 31990, "created_at": 1706620119, "tags": [["d", "7ab57c96fcb644c9d0d9ca0c93f40a863f7e8f6b33a4835b50ff3b3ac5c23129"], ["k", "30402"], ["web", "https://shopstr.store/<bech-32>", "npub"]], "content": "", "sig": "aa0dffe7c09c0053ba1ca61c56e1955f04b75d28602120937f780e2c391e5529c1fc8bd048b4b9abe5dcc25f281a8c6740466b86f5cc5cbfcc0833a4ebe3db71"}]]
```

Some of the testing I had done previously was spaced out by a couple of minutes so the redis cache entry had expired and the relay was running a fresh `SQL` query for each `REQ` which is why this went undetected. I was only able to reproduce the issue when making 2 requests withing 240 seconds (cache expiry period).

I have resolved that issue in #57 (results are live on `event_resp` branch and on `relay.nostpy.lol`) and tested with several different search strings and believe I have confirmed that:
* The `search` filter is now stored in the redis cache key
  * Prevents false positive from being returned when a subsequent search is made within 240 seconds
Example:
```
2024-05-11 16:41:33,863 - DEBUG - raw filters is {'kinds': [31990], 'search': 'https://shopstr.store/<bech-32>'}
2024-05-11 16:41:33,866 - DEBUG - Caching results , keys: {'kinds': [31990], 'search': 'https://shopstr.store/<bech-32>'}   value is : [[{"id": "a22aec54f45b1a33ebe2c7c545aa06aad9547f873810f933ed19d27ce489ad1f", "pubkey": "8b2ff7ceb4a1ea558bb929ce0d3513dfeca2cab712fd149551a961c822ace218", "kind": 31990, "created_at": 1706620119, "tags": [["d", "7ab57c96fcb644c9d0d9ca0c93f40a863f7e8f6b33a4835b50ff3b3ac5c23129"], ["k", "30402"], ["web", "https://shopstr.store/<bech-32>", "npub"]], "content": "", "sig": "aa0dffe7c09c0053ba1ca61c56e1955f04b75d28602120937f780e2c391e5529c1fc8bd048b4b9abe5dcc25f281a8c6740466b86f5cc5cbfcc0833a4ebe3db71"}]]
```

Hopefully this will close this issue out once and for all, please test when you have a chance and let me know if you are returning expected results.

Thanks!

**Comment by UTXOnly** [comment]
I'm going to mark this issue as closed now to merge into main. I have tested this under in several different way and seems to be working. But please don't hesitate to reopen or create a follow up issue if there are remaining issues.
